// Tile definitions for programmatic texture generation
// Each tile is 16x16 pixels, scaled 2x to 32x32

export const TILE_SIZE = 16;
export const TILE_SCALE = 2;
export const DISPLAY_TILE = TILE_SIZE * TILE_SCALE;

// Color palette - bright office theme
export const PALETTE = {
  floor1: '#d8cfc4',
  floor2: '#d0c7bb',
  wall: '#a09080',
  wallTop: '#b8a898',
  wallAccent: '#8a7a68',
  desk: '#8b6b4a',
  deskTop: '#b8945e',
  chair: '#6a5a48',
  table: '#7a5e3e',
  tableTop: '#c8a070',
  carpet: '#7a9ab8',
  carpet2: '#6e90b0',
  plant: '#5aaa6a',
  plantPot: '#b08040',
  screen: '#303848',
  screenGlow: '#70c8ff',
  door: '#9a8060',
  whiteboard: '#f0f0f0',
  whiteboardFrame: '#888898',
};

export interface TileData {
  key: string;
  pixels: string[];
  palette: Record<string, string>;
}

const floorPalette = {
  'a': PALETTE.floor1,
  'b': PALETTE.floor2,
};

const wallPalette = {
  'w': PALETTE.wall,
  't': PALETTE.wallTop,
  'a': PALETTE.wallAccent,
};

export const TILES: TileData[] = [
  {
    key: 'floor',
    pixels: [
      'aabbaaabbaabbbaa',
      'abbaabbaabaabbab',
      'baabaabbabbaabba',
      'aabbabbabaabbabb',
      'bbaabaabbabaabaa',
      'aababbaabbaaabba',
      'baabaabaabbabbab',
      'abbaabbabaabaaba',
      'baabaabbabbaabba',
      'aabbabbabaabbabb',
      'bbaabaabbabaabaa',
      'aababbaabbaaabba',
      'aabbaaabbaabbbaa',
      'abbaabbaabaabbab',
      'baabaabbabbaabba',
      'aabbabbabaabbabb',
    ],
    palette: floorPalette,
  },
  {
    key: 'wall',
    pixels: [
      'tttttttttttttttt',
      'tttttttttttttttt',
      'tttttttttttttttt',
      'tttttttttttttttt',
      'aaaaaaaaaaaaaaaa',
      'wwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwww',
    ],
    palette: wallPalette,
  },
  {
    key: 'carpet',
    pixels: [
      'aabbaaabbaabbbaa',
      'abbaabbaabaabbab',
      'baabaabbabbaabba',
      'aabbabbabaabbabb',
      'bbaabaabbabaabaa',
      'aababbaabbaaabba',
      'baabaabaabbabbab',
      'abbaabbabaabaaba',
      'baabaabbabbaabba',
      'aabbabbabaabbabb',
      'bbaabaabbabaabaa',
      'aababbaabbaaabba',
      'aabbaaabbaabbbaa',
      'abbaabbaabaabbab',
      'baabaabbabbaabba',
      'aabbabbabaabbabb',
    ],
    palette: { 'a': PALETTE.carpet, 'b': PALETTE.carpet2 },
  },
  {
    key: 'desk',
    pixels: [
      'dddddddddddddddd',
      'dtttttttttttttttd',
      'dtttttttttttttttd',
      'dtttttttttttttttd',
      'dtttttttttttttttd',
      'dtttttttttttttttd',
      'dtttttttttttttttd',
      'dtttttttttttttttd',
      'dddddddddddddddd',
      '..d..........d...',
      '..d..........d...',
      '..d..........d...',
      '..d..........d...',
      '..d..........d...',
      '.................',
      '.................',
    ],
    palette: { 'd': PALETTE.desk, 't': PALETTE.deskTop, '.': 'transparent' },
  },
  {
    key: 'computer',
    pixels: [
      '................',
      '....ssssssss....',
      '....sggggggs....',
      '....sggggggs....',
      '....sggggggs....',
      '....sggggggs....',
      '....ssssssss....',
      '......ssss......',
      '.....ssssss.....',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    palette: { 's': PALETTE.screen, 'g': PALETTE.screenGlow, '.': 'transparent' },
  },
  {
    key: 'table_conf',
    pixels: [
      'tttttttttttttttt',
      'tTTTTTTTTTTTTTTt',
      'tTTTTTTTTTTTTTTt',
      'tTTTTTTTTTTTTTTt',
      'tTTTTTTTTTTTTTTt',
      'tTTTTTTTTTTTTTTt',
      'tTTTTTTTTTTTTTTt',
      'tTTTTTTTTTTTTTTt',
      'tTTTTTTTTTTTTTTt',
      'tTTTTTTTTTTTTTTt',
      'tTTTTTTTTTTTTTTt',
      'tTTTTTTTTTTTTTTt',
      'tTTTTTTTTTTTTTTt',
      'tTTTTTTTTTTTTTTt',
      'tTTTTTTTTTTTTTTt',
      'tttttttttttttttt',
    ],
    palette: { 't': PALETTE.table, 'T': PALETTE.tableTop },
  },
  {
    key: 'plant',
    pixels: [
      '......gg........',
      '.....gggg.......',
      '....ggggg.gg....',
      '...ggggggggg....',
      '..gggggggggg....',
      '...gggggggg.....',
      '....ggggggg.....',
      '.....gggg.......',
      '......pp........',
      '......pp........',
      '.....pppp.......',
      '.....pppp.......',
      '.....pppp.......',
      '......pp........',
      '................',
      '................',
    ],
    palette: { 'g': PALETTE.plant, 'p': PALETTE.plantPot, '.': 'transparent' },
  },
  {
    key: 'whiteboard',
    pixels: [
      'ffffffffffffffff',
      'fwwwwwwwwwwwwwwf',
      'fwwwwwwwwwwwwwwf',
      'fwwwwwwwwwwwwwwf',
      'fwwwwwwwwwwwwwwf',
      'fwwwwwwwwwwwwwwf',
      'fwwwwwwwwwwwwwwf',
      'fwwwwwwwwwwwwwwf',
      'fwwwwwwwwwwwwwwf',
      'fwwwwwwwwwwwwwwf',
      'ffffffffffffffff',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    palette: { 'f': PALETTE.whiteboardFrame, 'w': PALETTE.whiteboard, '.': 'transparent' },
  },
];
